[package]
name = "wt_auto_extractor"
version = "0.1.0"
edition = "2021"
rust-version = "1.64"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "^0.5.9"
serde = { version = "^1.0.137", features = ["derive"]}
fs_extra = "^1.2.0"